// Detect Browser
var isOpera = !!window.opera || navigator.userAgent.indexOf(' OPR/') >= 0;
    // Opera 8.0+ (UA detection to detect Blink/v8-powered Opera)
var isFirefox = typeof InstallTrigger !== 'undefined';   // Firefox 1.0+
var isSafari = Object.prototype.toString.call(window.HTMLElement).indexOf('Constructor') > 0;
    // At least Safari 3+: "[object HTMLElementConstructor]"
var isChrome = !!window.chrome && !isOpera;              // Chrome 1+
var isIE = /*@cc_on!@*/false || !!document.documentMode;   // At least IE6

// Array sound
var arraySounds = [];
var arrayPersonnages = [];
var arrayDice = [];
var bg;
var type;
var chouette;

if(isChrome || isOpera){
    arraySounds = [
        'ogg/7_juste_pour_une_journee.ogg',
        'ogg/7cassedalle.ogg',
        'ogg/a_quel_point_de_vue.ogg',
        'ogg/ca_me_semble_assez_evident.ogg',
        'ogg/caca.ogg',
        'ogg/casse_dalle_de_la_nuit.ogg',
        'ogg/cb_casse_daille.ogg',
        'ogg/ceux_avec_la_nuit_11.ogg',
        'ogg/ceux_de_la_journee_pas_nuit.ogg',
        'ogg/fini_les_petite_mesure.ogg',
        'ogg/graine.ogg',
        'ogg/idee_commune',
        'ogg/je_vais_renserver_le_gouvernement.ogg',
        'ogg/jeunesse.ogg',
        'ogg/jvais_raser_le_territoire.ogg',
        'ogg/le_gras_sest_la_vie.ogg',
        'ogg/maitre_d_arme.ogg',
        'ogg/merde.ogg',
        'ogg/mieux_ne_pas_parler_comme_ca.ogg',
        'ogg/regne_de_la_peur.ogg',
        'ogg/rendez_compte_de_lexercice.ogg',
        'ogg/tres_bien.ogg',
        'ogg/venez_vous.ogg',
        'ogg/1.ogg',
        'ogg/2.ogg',
        'ogg/3.ogg',
        'ogg/4.ogg',
        'ogg/5.ogg',
        'ogg/19_solutions.ogg',
        'ogg/arreter_de_dire_des_trucs.ogg',
        'ogg/arthur2.ogg',
        'ogg/Arthurrr.ogg',
        'ogg/ca_me_fout_une_angoisse.ogg',
        'ogg/ca_vous_fatigue.ogg',
        'ogg/Cest-pas-faux.ogg',
        'ogg/cest_de_la_merde.ogg',
        'ogg/cest_de_la_merde.ogg',
        'ogg/chiant.ogg',
        'ogg/coche.ogg',
        'ogg/double.ogg',
        'ogg/echec.ogg',
        'ogg/essayer_de_developper_un_peu.ogg',
        'ogg/etre_considerer_comme_tel.ogg',
        'ogg/grolotine.ogg',
        'ogg/grolotine_rules.ogg',
        'ogg/il_ne_faut_plus_que_vous_parliez_comme_cela.ogg',
        'ogg/il_nous_a_chier_dessus.ogg',
        'ogg/independance.ogg',
        'ogg/je_pourrai_vous_tuer.ogg',
        'ogg/Mordu.ogg',
        'ogg/mordu2.ogg',
        'ogg/only.ogg',
        'ogg/partie.ogg',
        'ogg/pas_q.ogg',
        'ogg/petit_et_marron.ogg',
        'ogg/petit_q_perceval.ogg',
        'ogg/putain_il_est_fort_ce_con.ogg',
        'ogg/q_perceval.ogg',
        'ogg/qu_est_ce_c_est_cela.ogg',
        'ogg/qu_est_ce_que_ceci.ogg',
        'ogg/quoi.ogg',
        'ogg/sceau.ogg',
        'ogg/sloubi_karadoc.ogg',
        'ogg/sloubi_rules.ogg',
        'ogg/sortie.ogg',
        'ogg/un_marron.ogg',
    ];
    arrayPersonnages = [
        'ogg/faire_q.ogg',
        'ogg/go.ogg',
        'ogg/joue_3.ogg',
        'ogg/quoiquonjoue.ogg',
    ];
    arrayDice = [
      'ogg/lancer_1.ogg',
      'ogg/lancer_2.ogg',
      'ogg/lancer_3.ogg',
      'ogg/lancer_4.ogg',
    ];
    bg = 'bg_music.ogg';
    type = 'audio/ogg';
    chouette = 'ogg/q.ogg';
}
if(isFirefox || isIE){
    arraySounds = [
        '7_juste_pour_une_journee.mp3',
        '7cassedalle.mp3',
        'a_quel_point_de_vue.mp3',
        'ca_me_semble_assez_evident.mp3',
        'caca.mp3',
        'casse_dalle_de_la_nuit.mp3',
        'cb_casse_daille.mp3',
        'ceux_avec_la_nuit_11.mp3',
        'ceux_de_la_journee_pas_nuit.mp3',
        'fini_les_petite_mesure.mp3',
        'graine.mp3',
        'idee_commune',
        'je_vais_renserver_le_gouvernement.mp3',
        'jeunesse.mp3',
        'jvais_raser_le_territoire.mp3',
        'le_gras_sest_la_vie.mp3',
        'maitre_d_arme.mp3',
        'merde.mp3',
        'mieux_ne_pas_parler_comme_ca.mp3',
        'regne_de_la_peur.mp3',
        'rendez_compte_de_lexercice.mp3',
        'tres_bien.mp3',
        'venez_vous.mp3',
        '1.mp3',
        '2.mp3',
        '3.mp3',
        '4.mp3',
        '5.mp3',
        '19_solutions.mp3',
        'arreter_de_dire_des_trucs.mp3',
        'arthur2.mp3',
        'Arthurrr.mp3',
        'ca_me_fout_une_angoisse.mp3',
        'ca_vous_fatigue.mp3',
        'Cest-pas-faux.mp3',
        'cest_de_la_merde.mp3',
        'cest_de_la_merde.mp3',
        'chiant.mp3',
        'coche.mp3',
        'double.mp3',
        'echec.mp3',
        'essayer_de_developper_un_peu.mp3',
        'etre_considerer_comme_tel.mp3',
        'grolotine.mp3',
        'grolotine_rules.mp3',
        'il_ne_faut_plus_que_vous_parliez_comme_cela.mp3',
        'il_nous_a_chier_dessus.mp3',
        'independance.mp3',
        'je_pourrai_vous_tuer.mp3',
        'Mordu.mp3',
        'mordu2.mp3',
        'only.mp3',
        'partie.mp3',
        'pas_q.mp3',
        'petit_et_marron.mp3',
        'petit_q_perceval.mp3',
        'putain_il_est_fort_ce_con.mp3',
        'q_perceval.mp3',
        'qu_est_ce_c_est_cela.mp3',
        'qu_est_ce_que_ceci.mp3',
        'quoi.mp3',
        'sceau.mp3',
        'sloubi_karadoc.mp3',
        'sloubi_rules.mp3',
        'sortie.mp3',
        'un_marron.mp3',
    ];
    arrayDice = [
      'lancer_1.mp3',
      'lancer_2.mp3',
      'lancer_3.mp3',
      'lancer_4.mp3',
    ];
    arrayPersonnages = [
        'faire_q.mp3',
        'go.mp3',
        'joue_3.mp3',
        'quoiquonjoue.mp3',
    ];
    bg = 'bg_music.mp3';
    type = 'audio/mp3';
    chouette ='q.mp3';
}
if(isSafari){
    arraySounds = [
        'wav/7_juste_pour_une_journee.wav',
        'wav/7cassedalle.wav',
        'wav/a_quel_point_de_vue.wav',
        'wav/ca_me_semble_assez_evident.wav',
        'wav/caca.wav',
        'wav/casse_dalle_de_la_nuit.wav',
        'wav/cb_casse_daille.wav',
        'wav/ceux_avec_la_nuit_11.wav',
        'wav/ceux_de_la_journee_pas_nuit.wav',
        'wav/fini_les_petite_mesure.wav',
        'wav/graine.wav',
        'wav/idee_commune',
        'wav/je_vais_renserver_le_gouvernement.wav',
        'wav/jeunesse.wav',
        'wav/jvais_raser_le_territoire.wav',
        'wav/le_gras_sest_la_vie.wav',
        'wav/maitre_d_arme.wav',
        'wav/merde.wav',
        'wav/mieux_ne_pas_parler_comme_ca.wav',
        'wav/regne_de_la_peur.wav',
        'wav/rendez_compte_de_lexercice.wav',
        'wav/tres_bien.wav',
        'wav/venez_vous.wav',
        'wav/1.wav',
        'wav/2.wav',
        'wav/3.wav',
        'wav/4.wav',
        'wav/5.wav',
        'wav/19_solutions.wav',
        'wav/arreter_de_dire_des_trucs.wav',
        'wav/arthur2.wav',
        'wav/Arthurrr.wav',
        'wav/ca_me_fout_une_angoisse.wav',
        'wav/ca_vous_fatigue.wav',
        'wav/Cest-pas-faux.wav',
        'wav/cest_de_la_merde.wav',
        'wav/cest_de_la_merde.wav',
        'wav/chiant.wav',
        'wav/coche.wav',
        'wav/double.wav',
        'wav/echec.wav',
        'wav/essayer_de_developper_un_peu.wav',
        'wav/etre_considerer_comme_tel.wav',
        'wav/grolotine.wav',
        'wav/grolotine_rules.wav',
        'wav/il_ne_faut_plus_que_vous_parliez_comme_cela.wav',
        'wav/il_nous_a_chier_dessus.wav',
        'wav/independance.wav',
        'wav/je_pourrai_vous_tuer.wav',
        'wav/Mordu.wav',
        'wav/mordu2.wav',
        'wav/only.wav',
        'wav/partie.wav',
        'wav/pas_q.wav',
        'wav/petit_et_marron.wav',
        'wav/petit_q_perceval.wav',
        'wav/putain_il_est_fort_ce_con.wav',
        'wav/q_perceval.wav',
        'wav/qu_est_ce_c_est_cela.wav',
        'wav/qu_est_ce_que_ceci.wav',
        'wav/quoi.wav',
        'wav/sceau.wav',
        'wav/sloubi_karadoc.wav',
        'wav/sloubi_rules.wav',
        'wav/sortie.wav',
        'wav/un_marron.wav',
    ];
    arrayPersonnages = [
        'wav/faire_q.wav',
        'wav/go.wav',
        'wav/joue_3.wav',
        'wav/quoiquonjoue.wav',
    ];
    arrayDice = [
      'wav/lancer_1.wav',
      'wav/lancer_2.wav',
      'wav/lancer_3.wav',
      'wav/lancer_4.wav',
    ];
    bg = 'bg_music.wav';
    type = 'audio/wav';
    chouette = 'wav/q.wav';
}
